version: '3.8'

services:
  backend:
    image: bittenrichard/recrutamentoai-backend:latest
    networks:
      - Foco
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.recrutamentoai-backend.rule=Host(`recrutamentoia.com.br`) && PathPrefix(`/api`)"
        - "traefik.http.routers.recrutamentoai-backend.entrypoints=websecure"
        - "traefik.http.routers.recrutamentoai-backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.recrutamentoai-backend.loadbalancer.server.port=3001"
        - "traefik.http.routers.recrutamentoai-backend.middlewares=sslheader"
        - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      restart_policy:
        condition: on-failure
    environment:
      - VITE_BASEROW_API_KEY=anGucsRrFCKrOmUYHapVYsr5U3FVK85o
      - GOOGLE_CLIENT_ID=726048519835-4o31uj1ssftc47a08kcb8hs1hkm2v040.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_REDIRECT_URI=https://recrutamentoia.com.br/api/google/auth/callback
      - FRONTEND_URL=https://recrutamentoia.com.br
      - N8N_SCHEDULE_WEBHOOK_URL=https://webhook.focoserv.com.br/webhook/googleacesso
      - NODE_ENV=production

  frontend:
    image: bittenrichard/recrutamentoai-frontend:latest
    networks:
      - Foco
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.recrutamentoai-frontend.rule=Host(`recrutamentoia.com.br`) || Host(`www.recrutamentoia.com.br`)"
        - "traefik.http.routers.recrutamentoai-frontend.entrypoints=websecure"
        - "traefik.http.routers.recrutamentoai-frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.recrutamentoai-frontend.loadbalancer.server.port=80"
        - "traefik.http.routers.recrutamentoai-frontend.middlewares=sslheader"
        - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      restart_policy:
        condition: on-failure

networks:
  Foco:
    name: Foco
    external: true